#Q = https://datalemur.com/questions/top-fans-rank

WITH CTE AS (SELECT
A.ARTIST_NAME,
DENSE_RANK() OVER(ORDER BY COUNT(S.SONG_ID) DESC) ART_RNK
FROM ARTISTS A
JOIN SONGS S ON A.ARTIST_ID =S.ARTIST_ID
JOIN GLOBAL_SONG_RANK GS ON S.SONG_ID = GS.SONG_ID
WHERE GS.RANK <=10
GROUP BY A.ARTIST_NAME)
SELECT * FROM CTE WHERE ART_RNK <=5